import { React, useState } from "react";
import { getFarmProducts } from "../../data/productData";
import useLocalStorage from "../../fragments/customHook/useLocalStorage";
import { getData } from "../../data/repository";
import {useScrollToTop} from "../../fragments/customHook/useScrollToTop";
import ProductList from "../../components/ProductList";
import Product from "../../components/Product";

//Reference: The Growing Smaller Vegetables in Your Backyard content is generated by openAI.
const SpecialDeals = () => {
  useScrollToTop();
  const [farmProducts, setFarmProducts] = useState(getFarmProducts());
  useLocalStorage("SpecialProducts", farmProducts);
  const specialProducts = getData("SpecialProducts");

  return (
    <>
      <div className="text-center mt-5">
        <h2>Organic product specials & small-scale farming</h2>
      </div>
      <div class="container">
        <div class="row mx-5 mt-5">
          <div class="col">
            <h2>Growing Smaller Vegetables in Your Backyard</h2>
            
            <p>
              Have you ever dreamed of having a thriving vegetable garden right
              in your backyard, even with limited space? Growing smaller
              vegetables can be a rewarding and accessible way to enjoy fresh
              produce at home. In this blog post, we'll explore some tips and
              tricks for cultivating a bountiful harvest of compact vegetables
              in your own backyard oasis.
            </p>
            <div className="d-flex">
            <Product name={"D"} price={3} img={"https://picsum.photos/200/300"}/>
            <div className="p-4"></div>
            <Product name={"D"} price={3} img={"https://picsum.photos/200/300"}/>
          </div>
    
          </div>
          <div class="col"> <img src="https://picsum.photos/200/300" style={{width:"100%",height:"600px"}}></img></div>
          <div class="w-100"></div>
          <div class="col"> <img src="https://picsum.photos/200/300" style={{width:"100%",height:"600px"}}></img></div>
          <div class="col">
            <h2>Choosing the Right Vegetables</h2>
            <p>
              When space is a consideration, opting for smaller varieties of
              vegetables is key. Look for compact or dwarf varieties that thrive
              in containers or raised beds. Vegetables like cherry tomatoes,
              mini bell peppers, bush beans, and baby carrots are perfect
              choices for smaller spaces. These varieties not only fit well in
              confined areas but also yield delicious results that are perfect
              for salads, snacks, and cooking.
            </p>
          <div className="d-flex">
            <Product name={"D"} price={3} img={"https://picsum.photos/200/300"}/>
            <div className="p-4"></div>
            <Product name={"D"} price={3} img={"https://picsum.photos/200/300"}/>
          </div>
    
        
          </div>
          <div class="w-100"></div>
          <div class="col">
            <h2>Essential Tools and Accessories</h2>
            <p>
              To ensure success in your backyard vegetable garden, having the
              right tools and accessories is essential. Equip yourself with
              sturdy gardening gloves, a hand trowel, and pruning shears to
              tackle various gardening tasks comfortably. Our gardening gloves
              provide protection and comfort, while the hand trowel and pruning
              shears are designed for precision and ease of use. These tools
              will become invaluable companions as you nurture your vegetable
              plants to maturity.
            </p>
          </div>
          <div class="col"> <img src="https://picsum.photos/200/300" style={{width:"100%",height:"600px"}}></img></div>
        </div>
      </div>      
      <h2 className="text-center my-5">All Special Deal Items</h2>
      <ProductList list={specialProducts}></ProductList>
    </>
  );
};

export default SpecialDeals;
