import { React, useState } from "react";
import { getFarmProducts } from "../../data/productData";
import useLocalStorage from "../../fragments/customHook/useLocalStorage";
import { getData } from "../../data/repository";
import { useScrollToTop } from "../../fragments/customHook/useScrollToTop";
import ProductList from "../../components/ProductList";
import Product from "../../components/Product";
import Content from "./Content";
//Reference: The Growing Smaller Vegetables in Your Backyard content is generated by openAI.
const SpecialDeals = () => {
  useScrollToTop();
  //get special products(farm)
  const [farmProducts, setFarmProducts] = useState(getFarmProducts());
  console.log(farmProducts);
  //if there is a change in the repo, update the stat
  useLocalStorage("SpecialProducts", farmProducts);
  return (
    <>
      <div className="text-center mt-5">
        <h2>Organic product specials & small-scale farming</h2>
      </div>
      <div class="container">
        <div class="row mx-5 mt-5">
          <Content productId={[11,12]} head={"Growing Smaller Vegetables in Your Backyard"} content={`    Have you ever dreamed of having a thriving vegetable garden right
              in your backyard, even with limited space? Growing smaller
              vegetables can be a rewarding and accessible way to enjoy fresh
              produce at home. In this blog post, we'll explore some tips and
              tricks for cultivating a bountiful harvest of compact vegetables
              in your own backyard oasis.`}/>
          <div class="col">
            {" "}
            <img
              src="https://picsum.photos/200/300"
              style={{ width: "100%", height: "600px" }}
            ></img>
          </div>
          <div class="w-100 my-4"></div>
          <div class="col">
            {" "}
            <img
              src="https://picsum.photos/200/300"
              style={{ width: "100%", height: "600px" }}
            ></img>
          </div>
          <Content productId={[13,14]} head={"Choosing the Right Vegetables"} content={`    HWhen space is a consideration, opting for smaller varieties of
              vegetables is key. Look for compact or dwarf varieties that thrive
              in containers or raised beds. Vegetables like cherry tomatoes,
              mini bell peppers, bush beans, and baby carrots are perfect
              choices for smaller spaces. These varieties not only fit well in
              confined areas but also yield delicious results that are perfect
              for salads, snacks, and cooking.`}/>
            </div>
          <div class="w-100"></div>
          <div class="col">
            {" "}
          
          </div>
        </div>
      <h2 className="text-center my-5">All Special Deal Items</h2>
      <ProductList list={farmProducts}></ProductList>
    </>
  );
};

export default SpecialDeals;
